### ISSUE TITLE
What is the License of debase-ruby_core_source 0.10.2: MIT or Ruby?

### ISSUE THREAD

**Issue by luisapace** [os97673/debase-ruby_core_source#14]
Hi, my team would like to use the package debase-ruby_core_source 0.10.2 and to approve that I've to verify all its licenses (included those of all of the modules included), and to do that I've to analyze its source code.

Now I've noted that the package contains 3 license files: 
https://github.com/os97673/debase-ruby_core_source/blob/v0.10.2/LEGAL ---> Ruby's license or Public Domain (+ others), referring to Copying file, that does not exist;
https://github.com/os97673/debase-ruby_core_source/blob/v0.10.2/LICENSE.txt ----> MIT ;
https://github.com/os97673/debase-ruby_core_source/blob/v0.10.2/RUBY_LICENSE ---> BSD or Ruby.

Could you please clarify what is the license of debase-ruby_core_source 0.10.2?

Thanks a lot for your support.

**Comment by os97673** [comment]
The base idea is all files copied from ruby (all sub-directories of lib/debase/ruby_core_source) are under Ruby's license (with some exceptions if the file in ruby has different license),  a;ll ruby code of the gem is under MIT.  Please let me know if you have idea how to specify this in more accurate way.
Closing the ticket since I'm (kind of) answered the question.  Feel free to reopen if you have more question or file PR with suggested changes.
